from requests import get,post,delete,patch
cur_api_key = open('../data/current_api_key.txt', 'r').readline()
post('http://localhost:80/api/users',json={'api_key':cur_api_key,
                                                 'name':'Остап',
                                                 'surname':'Кормильцев',
                                                 'date_of_birth':'2003-01-04',
                                                 'email':'error1number404@gmail.com',
                                                 'password':'password',
                                                 'city_from':'Барнаул',
                                                 'country_from':180,
                                                 'friends':[]})
post('http://localhost:80/api/users',json={'api_key':cur_api_key,
                                                 'name':'Алексей',
                                                 'surname':'Шишкин',
                                                 'date_of_birth':'2002-10-17',
                                                 'email':'aa@gmail.com',
                                                 'password':'password',
                                                 'city_from':'Нижний Новгород',
                                                 'country_from':180,
                                                 'friends':[]})
patch('http://localhost:80/api/users',json={'api_key':cur_api_key,
                                                 'id':1,
                                                 'friends':[2]}) # создадим пользователей для тестов
print(post('http://localhost:80/api/tasks',json={'creator_id':1,
                                                  'title':'Title',
                                                  'type':1,
                                                  'description':'Description',
                                                  'participating':[2],
                                                  'date':'2021-05-10 16:00',
                                                  'address':'any address',
                                                  'country':180,
                                                  'is_private':True,
                                                  'is_address_displayed':False}).json()) # нет api ключа
print(post('http://localhost:80/api/tasks',json={'api_key':'wrong_api_key',
                                                  'creator_id':1,
                                                  'title':'Title',
                                                  'type':1,
                                                  'description':'Description',
                                                  'participating':[2],
                                                  'date':'2021-05-10 16:00',
                                                  'address':'any address',
                                                  'country':180,
                                                  'is_private':True,
                                                  'is_address_displayed':False}).json()) # неправильный api ключ
print(post('http://localhost:80/api/tasks',json={'api_key':cur_api_key,
                                                  'creator_id':1,
                                                  'title':'Title',
                                                  'type':1,
                                                  'description':'Description',
                                                  'participating':[2],
                                                  'is_address_displayed':False}).json()) # не все поля переданы на создание
print(post('http://localhost:80/api/tasks',json={'api_key':cur_api_key,
                                                  'creator_id':1,
                                                  'title':'Title',
                                                  'type':1,
                                                  'description':'Description',
                                                  'participating':[2],
                                                  'date':'2021-05-10 16-10',
                                                  'address':'any address',
                                                  'country':180,
                                                  'is_private':True,
                                                  'is_address_displayed':False}).json()) # неправильный формат даты
print(post('http://localhost:80/api/tasks',json={'api_key':cur_api_key,
                                                  'creator_id':1,
                                                  'title':'Title',
                                                  'type':1,
                                                  'description':'Description',
                                                  'participating':[1],
                                                  'date':'2021-05-10 16:10',
                                                  'address':'any address',
                                                  'country':180,
                                                  'is_private':True,
                                                  'is_address_displayed':False}).json()) # создатель не может быть в участниках
print(post('http://localhost:80/api/tasks',json={'api_key':cur_api_key,
                                                  'creator_id':88888,
                                                  'title':'Title',
                                                  'type':1,
                                                  'description':'Description',
                                                  'participating':[999999],
                                                  'date':'2021-05-10 16:00',
                                                  'address':'any address',
                                                  'country':180,
                                                  'is_private':True,
                                                  'is_address_displayed':False}).json()) # несуществующий пользователь в participating,creator_id
print(post('http://localhost:80/api/tasks',json={'api_key':cur_api_key,
                                                  'creator_id':1,
                                                  'title':'Title',
                                                  'type':88888888888,
                                                  'description':'Description',
                                                  'participating':[2],
                                                  'date':'2021-05-10 16:00',
                                                  'address':'any address',
                                                  'country':180,
                                                  'is_private':True,
                                                  'is_address_displayed':False}).json()) # несуществующий тип
print(post('http://localhost:80/api/tasks',json={'api_key':cur_api_key,
                                                  'creator_id':1,
                                                  'title':'Title',
                                                  'type':1,
                                                  'description':'Description',
                                                  'participating':[2],
                                                  'date':'2021-05-10 16:00',
                                                  'address':'any address',
                                                  'country':1805555555555555,
                                                  'is_private':True,
                                                  'is_address_displayed':False}).json()) # несуществующая страна
print(post('http://localhost:80/api/tasks',json={'api_key':cur_api_key,
                                                  'creator_id':1,
                                                  'title':'Title',
                                                  'type':1,
                                                  'description':'Description',
                                                  'participating':[2],
                                                  'date':'2021-05-10 16:00',
                                                  'address':'any address',
                                                  'country':'asdasdasd',
                                                  'is_private':True,
                                                  'is_address_displayed':False}).json()) # неверный формат country
print(post('http://localhost:80/api/tasks',json={'api_key':cur_api_key,
                                                  'creator_id':1,
                                                  'title':'Title',
                                                  'type':1,
                                                  'description':'Description',
                                                  'participating':[2],
                                                  'date':'2021-05-10 16:00',
                                                  'address':'any address',
                                                  'country':180,
                                                  'is_private':True,
                                                  'is_address_displayed':False}).json()) # все верно
print(post('http://localhost:80/api/tasks',json={'api_key':cur_api_key,
                                                  'creator_id':2,
                                                  'title':'Other Title',
                                                  'type':1,
                                                  'description':'Other Description',
                                                  'participating':[1],
                                                  'date':'2021-10-10 16:00',
                                                  'address':'different address',
                                                  'country':180,
                                                  'is_private':True,
                                                  'is_address_displayed':False}).json()) # все верно
print(patch('http://localhost:80/api/tasks',json={'api_key':cur_api_key,
                                                  'address':'new address'}).json()) # нет id
print(patch('http://localhost:80/api/tasks',json={'api_key':cur_api_key,
                                                  'id':'1'}).json()) # нет полей для редактирования
print(patch('http://localhost:80/api/tasks',json={'api_key':cur_api_key,
                                                  'id':'1',
                                                  'address':'new address'}).json()) # все верно
print(get('http://localhost:80/api/tasks/1',json={'api_key':cur_api_key}).json()) # все верно
print(get('http://localhost:80/api/tasks',json={'api_key':cur_api_key}).json()) # все верно
delete('http://localhost:80/api/users/1', json={'api_key':cur_api_key}) # удаляем созданных для тестов пользователей
delete('http://localhost:80/api/users/2', json={'api_key':cur_api_key})
